### ISSUE TITLE
Permissions appear to have a lengthy delay before a member can translate

### ISSUE THREAD

**Issue by LTIOfficial** [capiscuas/pootle#12]
I set up Aram (smartalgorithm) for Armenian TVP, but Pootle did not then provide him with the Suggest/Submit button, making it impossible for him to translate.  He shared his desktop with me via Skype and I took him through clearing browser cache (Google Chrome) and removing all Pootle cookies, but that was of no help.  We stopped maybe a half hour after I had set him up and he has since gone to sleep for the night.  As a result, I have no way of knowing if this is a delay or a more permanent bug.

He registered a while ago, so it's not a case of Pootle still processing his registration.

At the moment this report was created,

http://pootle.linguisticteam.org/about/memberstatus/  //Shows that he is still waiting for permissions setup

http://pootle.linguisticteam.org/hy/venus_project_site/admin_permissions.html  //Shows that he is already set up

http://pootle.linguisticteam.org/accounts/smartalgorithm/  //Also shows that he is already set up

**Comment by capiscuas** [comment]
This was a funny case we dealed with it, it seems that the pootle_cache may have been playing some tricks, deleting the user assigned permission and restoring it fixed the problem.

Please report similar thing in the future so we can find out which process fails restoring the pootle cache internally.
