### ISSUE TITLE
Contributors contains inaccurate info

### ISSUE THREAD

**Issue by LTIOfficial** [capiscuas/pootle#15]
I'm seeing numerous data on the Contributors page that is incorrect.
http://pootle.linguisticteam.org/about/contributors/

For example, it has me listed as a contributor for the Croatian TVP website project, but I am not listed in the Permissions page, nor do I show up in the drop-down box under "Project Members" or "Language Members".  I also do not have any languages or projects selected in my Settings page.

Also, the Arabic Tutorial has an entry that reads as "any anonymous user" and another for "Rabia Gawish", although there is no one set up under its permissions page.  This is not the only language Tutorial project that includes the 'anonymous user' entry, but it does not show up in all of them, even though Pootle is set to allow anonymous use/testing of this project across all languages.  In addition, there are some other non-Tutorial projects that also include this 'anonymous' inclusion.

There are more discrepencies, so consider the above as merely a sampling.

This may be functioning 'as designed' if it is only showing the members who have actually contributed to the projects that are shown, regardless of whether or not they are currently set up within those projects.

**Comment by capiscuas** [comment]
As discussed by chat, Contributors page comes from Pootle devs and it shows only those users that have contributed with 'Submits' and 'Suggestions'.

Which message would you like to put on top so we clarify that to the users that view this page?

**Comment by LTIOfficial** [comment]
A simple description of what the page shows is all that's needed.

"This page shows all Pootle members who have contributed directly to each project in each language, even if they are no longer associated with a given project.  Note that a contribution is viewed as the Suggesting or Submission of at least one string's translation within the project."

**Comment by capiscuas** [comment]
Fixed. 
Commit 4ec50da8cd1b730d4472d6051656c19a9917b7fc
