### ISSUE TITLE
Return of Users tab to provide coord view of language members

### ISSUE THREAD

**Issue by LTIOfficial** [capiscuas/pootle#18]
The Users tab is missing from the global areas for each language.  It provided info for each member including username, email, reg date, last log in and what the person had selected, with each listing linked directly to the admin permissions page for that project.

Also included was a custom email function that is no longer needed since that is now standard in the News tab.

Would prefer that the tab be renamed to "Members" instead of "Users".   ;)

**Comment by capiscuas** [comment]
Fixed.
For example for the SQ language admin:
http://pootle.linguisticteam.org/sq/users.html
