### ISSUE TITLE
Find out the Unknown Error ajax message that shows in the production server

### ISSUE THREAD

**Issue by capiscuas** [capiscuas/pootle#3]
It only shows in the English translationprojects.

**Comment by capiscuas** [comment]
When I opened the Pootle url with that Unknown Error
http://pootle.linguisticteam.org/en/english_proofreading/sample/translate.html#filter=incomplete
with the Google Chrome Inspect feature I was able to see what Ajax call was being done.

in the file settings/60-translation.conf
AMAGAMA_URL = 'http://amagama.locamotion.org/tmserver/' 

I reseted it to
AMAGAMA_URL = ''

beause that server is no longer active.
That removed the 'Unknown Error' ajax error.

Also http://translate.sourceforge.net/wiki/amagama/index seems to be only for small words and not long phrases(software/websites) like our LTI translations.

I suggest that the TranslationToolkit connections could be done only when small strings are being processed.

**Comment by LTIOfficial** [comment]
This bug is still present.  When I move from one string to the next, it produces the same 'unknown error' message.

**Comment by capiscuas** [comment]
Please add a link on the page that is producing the error :-)

**Comment by LTIOfficial** [comment]
http://pootle.linguisticteam.org/en/tutorial/translate.html#unit=556433

**Comment by capiscuas** [comment]
Apparently they were again 2 files of 60-translation.conf in the settings:

the settings/60-translation.conf
and the settings/60-translation-local.conf which had disabled the AMAGAMA_URL line.
I renamed 60-translation.conf to 60-translation.conf.delete so it won't be used and interfere.

I tried the link and it's not showing the Unknown error anymore to me.
